### ISSUE TITLE
Won't change existing custom sized pagefile

### ISSUE THREAD

**Issue by cwb124** [ptierno/puppet-windowspagefile#2]
Trying to get this to work on Server 2012 R2.  Our default image has a custom size specified of 1024GB page file, and I'd like to use puppet to increase it to 2048 or 4096.  Currently done with a powershell script.

Puppet code:
pagefile { 'c:\pagefile.sys':
    initialsize => 4096,
    maximumsize => 4096
    }

No matter what I do, the change doesn't apply.  Puppet shows success in the event log:

/Stage[main]/Winbuild/Pagefile[c:\pagefile.sys]/ensure: created

But the pagefile never changes, even after a reboot

**Comment by ptierno** [comment]
@cwb124 
Can you please supply the output of `puppet resource pagefile` on you `2012 R2` box?
Thanks

**Comment by cwb124** [comment]
So on a system that currently has 1024mb of pagefile, and a manifest with the above code, the output on that server is:  

C:\WINDOWS\system32>puppet resource pagefile
pagefile { 'c:\pagefile.sys':
  ensure        => 'present',
  initialsize   => '1024',
  maximumsize   => '1024',
  systemmanaged => 'false',
}

**Comment by ptierno** [comment]
@cwb124 
Thanks for that. So your saying on the system that you mentioned above, even though the pagefile is showing it is set to 1024, it is still really set to 2048? If possible can you provide a screenshot? I will spin up a 2012 box shortly to see if I can reproduce.

**Comment by ptierno** [comment]
@cwb124 
I was able to duplicate this. It appears that for some reason if you have already manually set a pagefile size, it is having trouble managing it via the provider. When i have time this weekend or next week I will address this. Thanks for bringing it to my attention.

**Comment by ptierno** [comment]
@cwb124 The issue appears to be munging the pagefile path parameter to capitalize the drive letter. Seems that on 2012 win32ole is returning a lower case drive letter. Not sure how this is an issue now and wasn't in the past. Just need to test changes on Server 2008 and then there will be a commit shortly following.

Thanks

**Comment by ptierno** [comment]
@cwb124 This issue is now resolved, see e9b4208
